### ISSUE TITLE
Week 8 Ready for review

### ISSUE THREAD

**Issue by palmerlarson** [palmerlarson/week8Restful-exercise#1]
Hi @pawaitemadisoncollege !

Week 8 is ready for review.

**What were your key learning points/takeaways?**
- RESTful API implementation.
**What challenged you?**
- I wanted to try and choose a different API for this exercise. I'm not sure if I chose the best API or not, there doesn't seem to be a lot of functionality with the free version but I may just be implementing it incorrectly. I chose https://nationalize.io/#overview for my API in this exercise (it returns a probability of what nationality the name is from). The free version is a bit limited so I altered the URI with get/set methods within the dao to change the user input.
**What problems did you solve and what resources did you use to solve them?**
- I came up with my own method of changing the input, I'm not sure if that's a correct method. Also, I'm not sure if my dao class is as optimized as it should be as there is no SQL dB involved on my end.

**Comment by pawaitemadisoncollege** [comment]
What a fun api you found, @palmerlarson! I haven't seen that one before!

Your pojos, dao and tests show that you've got a good handle on consuming a restful api in java. Regarding not having a DB on the backend: there may not be a good reason to store this kind of data if you can call the api and get whatever you need whenever you need it!

- [ ] I like that this test verifies a different response is returned based the name entered, I think it could be even better by also asserting the expected country names were returned along with the probability. 
https://github.com/palmerlarson/week8Restful-exercise/blob/1037229352de82f6f7f5c9c95f5eda705c1d03fb/src/test/java/com/palmerlarson/persistence/NationalizedaoTest.java#L56-L60

Maybe something like:
assertEquals("VE", countryTwo.get(0).getCountryId()); 
assertEquals(0.05786648552663837, countryTwo.get(0).getProbability()); 

Note: I did not test the code above, but hopefully that gives you an idea of how further testing could be done.
